.github/workflows/release.yml, .java_modules
=> Add java.management because redis breaks if it isn't there

README.md
And simplify docs so they use the cli
=> link to release in readme

src/bench/com/yetanalytics/xapipe/bench.clj, src/test/com/yetanalytics/xapipe/test_support.clj, src/test/com/yetanalytics/xapipe/test_support/lrs.clj
[PIP-42] In situations like benchmarks, we don't need a whole LRS to receive statements. Instead we can just have a convincing facade.
[PIP-42]: https://yet.atlassian.net/browse/PIP-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PIP-42 LRS Facade for test/bench

deps.edn
[PIP-44] Exclude clojurescript dep to save a little on size
[PIP-44]: https://yet.atlassian.net/browse/PIP-44?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Exclude CLJS DEP

deps.edn, src/lib/com/yetanalytics/xapipe.clj, src/lib/com/yetanalytics/xapipe/client/multipart_mixed.clj
[PIP-45] Rather than bring in the whole `byte-streams` dep, let's form the inputstream for apache http ourselves using a simple future.
[PIP-45]: https://yet.atlassian.net/browse/PIP-45?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PIP-45 PipedInputStream POST body

README.md, demo/dashboard.yaml, demo/datasource.yaml, demo/docker-compose.yml, demo/grafana.ini, demo/prometheus.yml, demo/xapipe_dashboard.json, deps.edn, src/cli/com/yetanalytics/xapipe/cli.clj, src/cli/com/yetanalytics/xapipe/cli/options.clj, src/cli/com/yetanalytics/xapipe/main.clj, src/cli/com/yetanalytics/xapipe/metrics/impl/prometheus.clj, src/lib/com/yetanalytics/xapipe.clj, src/lib/com/yetanalytics/xapipe/client.clj, src/lib/com/yetanalytics/xapipe/metrics.clj, src/lib/com/yetanalytics/xapipe/util/async.clj, src/test/com/yetanalytics/xapipe/cli/options_test.clj, src/test/com/yetanalytics/xapipe/main_test.clj
Support extensible (in clojure) metrics, and implement prometheus push as an option in the CLI
=> PIP-15 Metrics Support & Prometheus

demo/docker-compose.yml
=> Add persistence for prometheus and grafana in demo

.github/workflows/ci.yaml, Makefile, deps.edn, src/build/com/yetanalytics/xapipe/build.clj
[PIP-51] The transition was.. easier than expected.
[PIP-51]: https://yet.atlassian.net/browse/PIP-51?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[tools.build Guide](https://clojure.org/guides/tools_build)
=> PIP-51 depstar -> tools.build

.github/workflows/ci.yaml, .github/workflows/docker.yml, .github/workflows/release.yml, README.md
Create docker images orthogonally from the release workflow. Build for tags, branches.
=> Gh actions docker overhaul

doc/options.md, src/cli/com/yetanalytics/xapipe/cli/options.clj, src/cli/com/yetanalytics/xapipe/main.clj, src/lib/com/yetanalytics/xapipe/job/json.clj, src/test/com/yetanalytics/xapipe/main_test.clj
[PIP-67] Allow user to export job as a json file
[PIP-67]: https://yet.atlassian.net/browse/PIP-67?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PIP-67 Job JSON output

dev-resources/profiles/calibration_concept.jsonld
couple of minor fixes for instrumentation with rules
=> PIP-70 - concept profile fix

.github/workflows/ci.yml, deps.edn
It should call over to our actions repo
Waiting on https://github.com/yetanalytics/actions/pull/2 for version tag `v1`
=> PIP-74 Migrate NVD Scanning to reusable workflow

.github/workflows/nvd_sched.yml
[PIP-74] Nvd scans should happen periodically
[PIP-74]: https://yet.atlassian.net/browse/PIP-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PIP-74 scheduled nvd scan

.github/workflows/ci.yml, .github/workflows/nvd_sched.yml, .github/workflows/release.yml
Update to the latest nvd scan reusable workflow, release ver when it comes out!
=> update to latest nvd scan in ci

src/cli/com/yetanalytics/xapipe/main.clj
[PIP-76] Don't leak the full job as it might contain creds.
[PIP-76]: https://yet.atlassian.net/browse/PIP-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PIP-76 sanitize job before spec output

doc/json.md, src/cli/com/yetanalytics/xapipe/main.clj, src/lib/com/yetanalytics/xapipe/job.clj, src/test/com/yetanalytics/xapipe/cli_test.clj, src/test/com/yetanalytics/xapipe/job_test.clj, src/test/com/yetanalytics/xapipe/main_test.clj
[PIP-68] We may need to make breaking changes to job specs, so let's use a simple integer version for breaking changes + upgrades
[PIP-68]: https://yet.atlassian.net/browse/PIP-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PIP-68 Simple Job Versioning + Upgrade

.github/workflows/ci.yml, .github/workflows/nvd_sched.yml, .github/workflows/release.yml
[PIP-78] Some github action housekeeping in prep for further updates.
[PIP-78]: https://yet.atlassian.net/browse/PIP-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PIP-78 Github Actions Updates

.github/workflows/ci.yml, deps.edn, doc/index.md, doc/oauth.md, doc/options.md, src/cli/com/yetanalytics/xapipe/cli.clj, src/cli/com/yetanalytics/xapipe/cli/options.clj, src/cli/com/yetanalytics/xapipe/main.clj, src/lib/com/yetanalytics/xapipe.clj, src/lib/com/yetanalytics/xapipe/client.clj, src/lib/com/yetanalytics/xapipe/client/oauth.clj, src/test/com/yetanalytics/xapipe/cli/options_test.clj, src/test/com/yetanalytics/xapipe/cli_test.clj
[PIP-79] Support the OAuth 2.0 Client Credentials Grant
[Docs!](https://github.com/yetanalytics/xapipe/blob/PIP-79/doc/oauth.md)
[PIP-79]: https://yet.atlassian.net/browse/PIP-79?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PIP-79 OAuth Client Credentials & Token Support

.nvd/suppression.xml
See https://github.com/jeremylong/DependencyCheck/issues/5502
=> CVE-2022-45688 add suppression for FP on jackson

README.md, resources/doc/docs.html.template
year on readme, and autogen year on docs
=> [PIP-83] Year updates

.nvd/suppression.xml
- Suppress false positives for CVE-2017-20189
- Remove now-unneeded suppressions
=> Add suppression for non-Clojure lib CVE FPs

deps.edn
update to latest carmine to clear CVE-2024-36124
=> update to latest carmine to clear CVE-2024-36124

deps.edn
bump logback for cve CVE-2024-12798
=> bump logback for cve CVE-2024-12798
