src/cli/com/yetanalytics/xapipe/main.clj
src/lib/com/yetanalytics/xapipe/job.clj
src/lib/com/yetanalytics/xapipe/job/config.clj
src/lib/com/yetanalytics/xapipe/job/state/errors.clj
src/test/com/yetanalytics/xapipe/job/config_test.clj
src/test/com/yetanalytics/xapipe/job_test.clj

[PIP-40]
Output is obscured like so:
```clojure
bin/run.sh --source-url http://0.0.0.0:8080/xapi --source-username foo --s
ource-password bar --target-url http://0.0.0.0:8081/xapi --target-username foo --target-password
bar
Nov 10, 2021 4:27:30 PM com.yetanalytics.xapipe.main invoke
INFO: Created new job 5082ac79-4d59-4b14-adbf-ae8d104685c1: {:id "5082ac79-4d59-4b14-adbf-ae8d104685c1", :config {:get-buffer-size 10, :statement-buffer-size 500, :batch-buffer-size 10, :batch-timeout 200, :source {:request-config {:url-base "http://0.0.0.0:8080", :xapi-prefix "/xapi", :username "foo", :password "************"}, :get-params {:limit 50}, :poll-interval 1000, :batch-size 50, :backoff-opts {:budget 10000, :max-attempt 10}}, :target {:request-config {:url-base "http://0.0.0.0:8081", :xapi-prefix …
```

PIP-40 obscure LRS passwords in logs

---

.github/workflows/release.yml
Makefile
src/cli/logback.xml

A few misc dev + performance tweaks, none of which need a new version:
* use single modules list from file in dev + release scripting
* Don't download old LRSQL jre
* Turn off prod logback file scanning

Tweaks 2021-11-10

---

src/lib/com/yetanalytics/xapipe/client.clj
src/test/com/yetanalytics/xapipe/main_test.clj

[PIP-47] Just like we have retry-able statuses, we should treat some client exceptions as retry-able. For now that's just `ConnectionError`
[PIP-47]: https://yet.atlassian.net/browse/PIP-47?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIP-47 Retry on Conn Errors

---

deps.edn
src/lib/com/yetanalytics/xapipe/client.clj

[PIP-50]
While xapipe's cursor only advances on the receipt of data, the GET loop maintains its own cursor, which was pulling ahead according to the consistent-through header. In a perfect world we could trust it, but alas.
This PR explicitly binds a new since which is either the last stored time of a received batch or the previous since.
[PIP-50]: https://yet.atlassian.net/browse/PIP-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIP-50 Don't use consistent-through header to advance GET loop

---

src/cli/com/yetanalytics/xapipe/metrics/impl/prometheus.clj
src/lib/com/yetanalytics/xapipe.clj
src/lib/com/yetanalytics/xapipe/metrics.clj

* Our prometheus client wrapper's examples made it seem like it was immutable and needed to be threaded. It is not/does not. Adapt impls and specs to reflect that
* There were questions about whether the exporter needed to run in a thread, after looking at the upstream source it does not.

PIP-52 minor metrics refactor

---

src/lib/com/yetanalytics/xapipe.clj
src/lib/com/yetanalytics/xapipe/metrics.clj

[PIP-55] If the reporter isn't configured properly, the flush action may throw at runtime. Just warn about this if it happens
[PIP-55]: https://yet.atlassian.net/browse/PIP-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIP-55 catch and log all errors on metrics flush

---

src/lib/com/yetanalytics/xapipe/xapi.clj
src/test/com/yetanalytics/xapipe/xapi_test.clj

[PIP-54] If the source LRS sends us extra attachments, delete them. This shouldn't happen but multipart/mixed impls vary widely
[PIP-54]: https://yet.atlassian.net/browse/PIP-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIP-54 delete any extra attachments

---

src/lib/com/yetanalytics/xapipe/client.clj

[PIP-57] Our `clj-http` resp handler tries to parse responses as multiparts in some contexts. It should only do that on a 200.
[PIP-57]: https://yet.atlassian.net/browse/PIP-57?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIP-57 Don't parse non-200 multipart responses

---

doc/options.md
doc/usage.md
src/cli/com/yetanalytics/xapipe/cli.clj
src/cli/com/yetanalytics/xapipe/cli/options.clj
src/lib/com/yetanalytics/xapipe/filter.clj
src/lib/com/yetanalytics/xapipe/filter/path.clj
src/test/com/yetanalytics/xapipe/cli/options_test.clj
src/test/com/yetanalytics/xapipe/filter/path_test.clj

[PIP-56] Add a simple JsonPath presence filter that ensures that only statements with a value at the given path will be passed
See updated docs here: https://github.com/yetanalytics/xapipe/blob/PIP-56/doc/usage.md#jsonpath-presence-filtering and here: https://github.com/yetanalytics/xapipe/blob/PIP-56/doc/usage.md#jsonpath-matching and here: https://github.com/yetanalytics/xapipe/blob/PIP-56/doc/options.md
[PIP-56]: https://yet.atlassian.net/browse/PIP-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIP-56 Simple JsonPath filter

---

.gitignore
Makefile
deps.edn
src/bench/com/yetanalytics/xapipe/bench.clj
src/lib/com/yetanalytics/xapipe.clj
src/lib/com/yetanalytics/xapipe/job/state.clj
src/lib/com/yetanalytics/xapipe/util/time.clj
src/test/com/yetanalytics/xapipe/main_test.clj
src/test/com/yetanalytics/xapipe/test_support.clj
src/test/com/yetanalytics/xapipe/test_support/lrs.clj
src/test/com/yetanalytics/xapipe_test.clj

[PIP-60] Devise a benchmark solely concerned with statement throughput
The new benchmark will:
1. Create a JSON payload of statements
2. Stream those statements out of a facade LRS
Like so:
```shell
$ make clean bench
rm -rf target dev-resources/bench/*.json
clojure -Xtest:bench write-payload \
:num-statements 10000 \
:profile '"dev-resources/profiles/calibration.jsonld"' \
:out '"dev-resources/bench/payload.json"'
clojure -Xtest:bench run-bench \
:num-statements 10000 \
:payload-path '"dev-resources/bench/payload.json"'
Initializing source LRS from dev-resources/bench/payload.json
| statements | total time (ms) |  s/sec throughput |
|------------+-----------------+-------------------|
|      10000 |            3164 | 3160.556257901391 |
```
Also adds an `:updated` timestamp to the job …

PIP-60 Throughput benchmark

---

Makefile
src/bench/com/yetanalytics/xapipe/bench.clj

[PIP-62] When I switched the benchmarks over from conf data, I removed the stats and warmup. This brings back limited averages in the form of a matrix-style benchmark that can be used to compare tunings
```shell
➜  xapipe git:(PIP-62) ✗ make bench
clojure -Xtest:bench run-bench-matrix \
:num-statements 10000 \
:payload-path '"dev-resources/bench/payload.json"'
defaults warmup x 5 |||||
defaults run x 10 ||||||||||
|    label | runs | statements | src batch | get buf | s buf | batch buf | batch ms | tgt batch | total t (ms) |             s/sec |
|----------+------+------------+-----------+---------+-------+-----------+----------+-----------+--------------+-------------------|
| defaults |   10 |      10000 |        50 |      10 |   500 |        10 |      200 |        50 |       1791.9 | …
```

PIP-62 matrix-based averaging benchmark

---

.github/workflows/ci.yaml
.java_modules
Makefile
bin/run.sh
src/test/com/yetanalytics/xapipe/filter_test.clj

We've been testing with whatever modules the dev has laying around on their machine. To be closer to the custom runtime we can restrict the modules used when running tests.
Update: Adding `jvm.crypto.ec` as mentioned in https://stackoverflow.com/questions/68896945/javax-net-ssl-sslhandshakeexception-happening-when-using-custom-java-runtime-ima allows TLS 1.3 or 1.2 without issue.

PIP-63 Restrict Java Modules in Test

---

src/cli/com/yetanalytics/xapipe/cli.clj
src/test/com/yetanalytics/xapipe/cli_test.clj
src/test/com/yetanalytics/xapipe/main_test.clj

[PIP-65] The assoc path was incorrect, meaning the buffer + batch timeout settings would get dropped
[PIP-65]: https://yet.atlassian.net/browse/PIP-65?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIP-65 Bug: settings provided for restarted jobs are ignored

---

.github/workflows/nvd_sched.yml

bump version of NVD in scheduled scan

---

.github/workflows/ci.yml
.github/workflows/nvd_sched.yml
.nvd/config.json
.nvd/suppression.xml
deps.edn

- Remove CVE-2020-36518 by updating Cheshire and Jackson dependencies
- Suppress CVE-2021-43138 by adding NVD config
- Add Slack notifications to periodic NVD scanning (~**TODO:** Need to add the `SLACK_WORFKLOW_URL` secret~ Done!)

NVD scan update

---

deps.edn
src/lib/com/yetanalytics/xapipe/filter.clj
src/lib/com/yetanalytics/xapipe/filter/concept.clj

[LRS-72] Update testing to use `lrs` version `1.2.11` with in-memory LRSs that handle and return deduped attachments.
Other dep updates as needed, including fixes for namespaces + changed specs in Pan.
[LRS-72]: https://yet.atlassian.net/browse/LRS-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LRS-72 testing updates for deduplicated attachments, pan fixes

---

.nvd/suppression.xml

Another day, two more clojure libs falsely identified as vulnerable.

suppress CVE-2022-23172, CVE-2022-23173 on priority map libs

---

deps.edn

Likely an FP, but we don't use the msgpack functionality in `transit-clj`. https://nvd.nist.gov/vuln/detail/CVE-2022-41719

exclude msgpack to clear CVE-2022-41719

---

.github/workflows/ci.yml
.github/workflows/nvd_sched.yml
.github/workflows/release.yml

- Replaced deprecated `set-output` command
- Updated the following actions and composite workflows:
- runtimer workflow to 0.1.2-java-11-temurin
- nvd-scan workflow to v0.0.4
- yetanalytics/actions/setup-env to v0.0.4
- actions/cache from v2 to v3
- actions/download-artifact from v2 to v3
- actions/upload-artifact from v2 to v3
- JamesIves/github-pages-deploy-action` to v4.4.1
- docker/login-action to v2
- docker/metadata-action to v4
- docker/build-push-action to v3
- slackapi/slack-github-action to v1.23.0
- Update OS versions:
- Windows from 2019 to 2022
- MacOS from 10.15 to 11

[PIP-82] Update CI/CD

---

deps.edn

https://nvd.nist.gov/vuln/detail/CVE-2023-24998
https://lists.apache.org/thread/4xl4l09mhwg4vgsk7dxqogcjrobrrdoy

CVE-2023-24998 update commons-fileupload to 1.5

---

dev-resources/templates/lrspipe_ec2.yml

Version default in template was quite old, bring it up to current.

update CloudFormation template to use v0.0.25

---

.github/workflows/deps.yml
Makefile

[PIP-88] Devise a method for providing dependency graph information to github.
This PR:
* Adds a Makefile target that creates a `pom.xml` with the aliases used in the release build
* Uses that pom to submit dependency graph information to GitHub
[PIP-88]: https://yet.atlassian.net/browse/PIP-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PIP-88 Dependency Graph Support

---

deps.edn

We updated logback without the corresponding update to slf4j. This fixes that.

Update slf4j API to fix failing runtime

---

deps.edn

The clojure core team has added mitigation for CVE-2024-22871 in version 1.11.2

update clojure to clear CVE-2024-22871

---

deps.edn

Resolves CVE-2024-47554, which dependabot didn't catch.

pin commons io to clear CVE-2024-47554

---

.github/workflows/ci.yml
.github/workflows/deps.yml
.github/workflows/release.yml
.gitignore

Update the runtimer workflow to the latest repo and version, in order to use non-deprecated versions of MacOS and other operating systems. In addition, update important (not every) action, including all `actions/` actions and `yetanalytics/actions/setup-env`.
Also kill CI on pull requests since it's redundant, since we already do CI on each push.

Update runtimer and other actions
